### PR TITLE
Fix stdin bug with windows git bash

### LINKED ISSUE #402: `HasStdin()` always returns true in Windows Git Bash
`fileutil.HasStdin()` return __true__ even if there's no std input. This happens specifically with Git Bash in Windows.
Screenshot 2024-05-02 041134

Ref: https://stackoverflow.com/questions/22744443/check-if-there-is-something-to-read-on-stdin-in-golang

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes #402 
- Indirectly solves https://github.com/projectdiscovery/dnsx/issues/345

### CODE REVIEW

File: file/file.go [hunk 1]
```diff
@@ -177,6 +179,9 @@ func CreateFolder(path string) error {
 
 // HasStdin determines if the user has piped input
 func HasStdin() bool {
+	if runtime.GOOS == "windows" && (isatty.IsTerminal(os.Stdin.Fd()) || isatty.IsCygwinTerminal(os.Stdin.Fd())) {
```
Comment (dogancanbakir) [inline file/file.go:182]: we can use osutils here https://github.com/projectdiscovery/utils/blob/1e40ad2773366a23c63a419611671e63d36a409c/os/os.go#L55

**Review by dogancanbakir — APPROVED** [review]
left a comment -minor

**Review by ehsandeep — APPROVED** [review]
